### ISSUE TITLE
Deleting a Submission doesn't delete the corresponding SubmissionInfo

### ISSUE THREAD

**Issue by alexkiro** [eaudeweb/ozone#417]
Whenever a Submission is deleted the corresponding SubmissionInfo is not removed. This isn't causing any issues (yet) that I can tell in the application itself, but querying the SubmissionInfo table does raise an error.

```python
>>> SubmissionInfo.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/alexandru/PycharmProjects/ozone/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 247, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
  File "/home/alexandru/PycharmProjects/ozone/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 503, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
  File "/home/alexandru/PycharmProjects/ozone/ozone/core/models/reporting.py", line 93, in __str__
    return f'{self.submission} - Info'
  File "/home/alexandru/PycharmProjects/ozone/.venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 414, in __get__
    self.related.get_accessor_name()
ozone.core.models.reporting.SubmissionInfo.submission.RelatedObjectDoesNotExist: SubmissionInfo has no submission.

```

**Comment by sorinstelian** [comment]
:+1:
